blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Votura Community Support
    url: https://github.com/SE-UUlm/votura-crypto/discussions/categories/q-a
    about: Please ask and answer questions here.
